# Generated by Django 3.1.7 on 2021-03-31 07:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Featured',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('restaurant', models.CharField(default='', max_length=100)),
                ('foods', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=500, null=True)),
                ('rest_photo', models.ImageField(default='default.png', upload_to='user_photos')),
                ('rest_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('alternate_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('rest_Address', models.TextField()),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('rest_area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('Bagmati', 'Bagmati')], max_length=50, null=True)),
                ('rest_opentime', models.TimeField(blank=True, null=True)),
                ('rest_closetime', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('closed', 'Close'), ('open', 'Open')], default='open', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='rest_reg_date')),
                ('account_Holder_Name', models.CharField(max_length=50, null=True)),
                ('account_Number', models.CharField(max_length=20, null=True)),
                ('rest_merchant_id', models.IntegerField(blank=True, null=True)),
                ('rest_reg_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('rest_reg_date',),
            },
        ),
        migrations.CreateModel(
            name='restMenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='restFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(default='', max_length=100)),
                ('food_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(db_index=False, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='foods/images')),
                ('food_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('food_price', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restmenumodel')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.restaurant')),
            ],
        ),
    ]
