# Generated by Django 3.1.7 on 2021-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20210331_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restfoodmodel',
            name='food_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='foods/images'),
        ),
    ]
