# Generated by Django 3.1.7 on 2021-04-05 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210403_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restfoodmodel',
            name='food_image',
            field=models.ImageField(blank=True, default='foods/images/default.png', null=True, upload_to='foods/images'),
        ),
    ]
