# Generated by Django 3.1.7 on 2021-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20210405_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_Address',
            field=models.CharField(max_length=250),
        ),
    ]
