# Generated by Django 3.1.7 on 2021-04-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20210412_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmenumodel',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.restaurant'),
        ),
    ]
