# Generated by Django 3.1.7 on 2021-04-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20210414_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restfoodmodel',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodmenu', to='restaurants.restmenumodel'),
        ),
    ]
