# Generated by Django 3.1.7 on 2021-05-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20210503_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='amount',
        ),
    ]
