# Generated by Django 3.1.7 on 2021-05-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210507_1305'),
        ('restaurants', '0013_auto_20210506_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_paid', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restfoodmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.orders')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurant')),
            ],
        ),
    ]
