# Generated by Django 3.1.7 on 2021-04-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210405_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default='user_photos/nouser.jpg', upload_to='user_photos'),
        ),
    ]
