# Generated by Django 3.1.7 on 2021-05-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20210504_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('stret_address', models.TextField()),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('Bagmati', 'Bagmati')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
