# Generated by Django 3.1.7 on 2021-05-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210507_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='stret_address',
            new_name='street_address',
        ),
    ]
